
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: lb://microservice1
          predicates:
            - Path=/micro1/**
          filters:
            - StripPrefix=1

        - id: consumerModule
          uri: lb://microservice2
          predicates:
            - Path=/micro2/**
          filters:
            - StripPrefix=1